/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.ButtonGroup;
import models.Clothing;
import models.DBManager;
import models.Footwear;
import models.Staff;

/**
 *
 * @author Aidan
 */
public class AddProduct extends javax.swing.JFrame {

    
    private static Staff staff;
    private ButtonGroup bg;
    
    /**
     * Creates new form AddProduct
     */
    public AddProduct(Staff s) {
        this.staff = s;
        initComponents();
        this.setLocationRelativeTo(null);
        
        bg = new ButtonGroup();
        bg.add(rdoClothing);
        bg.add(rdoFootwear);
        
        lblMeasureSize.setVisible(false);
        txtMeasureSize.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMeasureSize = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtStockLevel = new javax.swing.JTextField();
        txtMeasureSize = new javax.swing.JTextField();
        rdoClothing = new javax.swing.JRadioButton();
        rdoFootwear = new javax.swing.JRadioButton();
        cmdSubmit = new javax.swing.JButton();
        cmdBack = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add new product");

        jLabel2.setText("Type of product:");

        jLabel3.setText("Name:");

        jLabel4.setText("Price:");

        jLabel5.setText("Stock Level:");

        lblMeasureSize.setText("jLabel6");

        rdoClothing.setText("Clothing");
        rdoClothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoClothingActionPerformed(evt);
            }
        });

        rdoFootwear.setText("Footwear");
        rdoFootwear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFootwearActionPerformed(evt);
            }
        });

        cmdSubmit.setText("Submit");
        cmdSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSubmitActionPerformed(evt);
            }
        });

        cmdBack.setText("Back");
        cmdBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackActionPerformed(evt);
            }
        });

        cmdClear.setText("Clear");
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        lblErrorMessage.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdBack)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(lblMeasureSize)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtPrice)
                                    .addComponent(txtStockLevel)
                                    .addComponent(txtMeasureSize)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoClothing)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdoFootwear))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(cmdSubmit))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblErrorMessage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(cmdClear)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdoClothing)
                    .addComponent(rdoFootwear))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdClear)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMeasureSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMeasureSize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(lblErrorMessage)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackActionPerformed
        ModifyProducts vps = new ModifyProducts(staff);
        this.dispose();
        vps.setVisible(true);
    }//GEN-LAST:event_cmdBackActionPerformed

    private void rdoClothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoClothingActionPerformed
        lblMeasureSize.setVisible(true);
        txtMeasureSize.setVisible(true);
        
        lblMeasureSize.setText("Measuremeant:");
    }//GEN-LAST:event_rdoClothingActionPerformed

    private void rdoFootwearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFootwearActionPerformed
        lblMeasureSize.setVisible(true);
        txtMeasureSize.setVisible(true);
        
        lblMeasureSize.setText("Size:");
    }//GEN-LAST:event_rdoFootwearActionPerformed

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        txtName.setText("");
        txtPrice.setText("");
        txtStockLevel.setText("");
        txtMeasureSize.setText("");
        
        bg.clearSelection();
        
        lblMeasureSize.setVisible(false);
        txtMeasureSize.setVisible(false);
    }//GEN-LAST:event_cmdClearActionPerformed

    private void cmdSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSubmitActionPerformed
        String name = txtName.getText();
        String price = txtPrice.getText();
        String stockLevel = txtStockLevel.getText();
        String MeasureSize = txtMeasureSize.getText();
        
        DBManager db = new DBManager();
        
        if(!rdoClothing.isSelected() && !rdoFootwear.isSelected()) 
            lblErrorMessage.setText("Error: Please select type of product");
        else if(name.equals("") || price.equals("") || stockLevel.equals("") || MeasureSize.equals(""))
            lblErrorMessage.setText("Error: Please fill out all data");
        else
        {
            try 
            {
                double doublePrice = Double.parseDouble(price);
                
                try 
                {
                    int intStockLevel = Integer.parseInt(stockLevel);
                    
                    if(rdoFootwear.isSelected())
                    {
                        try 
                        {
                            int intSize = Integer.parseInt(MeasureSize);
                            
                            Footwear f = new Footwear(intSize, name, doublePrice, intStockLevel);
                            db.addProduct(f);
                            
                            ModifyProducts mp = new ModifyProducts(staff);
                            this.dispose();
                            mp.setVisible(true);
                            
                        }
                        catch (Exception e) 
                        {
                            lblErrorMessage.setText("Error: Please enter number for size");
                        }
                    }
                    else
                    {
                        Clothing c = new Clothing(MeasureSize, name, doublePrice, intStockLevel);
                        db.addProduct(c);
                        
                        ModifyProducts mp = new ModifyProducts(staff);
                        this.dispose();
                        mp.setVisible(true);
                    }
                } 
                catch (Exception e) 
                {
                    lblErrorMessage.setText("Error: Please enter number for stock level");
                }
            } 
            catch (Exception e) 
            {
                lblErrorMessage.setText("Error: Please enter decimal for price");
            }
        }
    }//GEN-LAST:event_cmdSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct(new Staff()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBack;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblMeasureSize;
    private javax.swing.JRadioButton rdoClothing;
    private javax.swing.JRadioButton rdoFootwear;
    private javax.swing.JTextField txtMeasureSize;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStockLevel;
    // End of variables declaration//GEN-END:variables
}
