/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import models.Customer;
import models.DBManager;

/**
 *
 * @author Aidan
 */
public class CustomerHome extends javax.swing.JFrame {

    private static Customer customer;
    
    /**
     * Creates new form CustomerHome
     */
    public CustomerHome(Customer c) {
        this.customer = c;
        initComponents();
        lblWelcome.setText(c.displayGreeting());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        cmdBrowseProducts = new javax.swing.JButton();
        cmdViewOrders = new javax.swing.JButton();
        cmdEditDetails = new javax.swing.JButton();
        cmdUnregister = new javax.swing.JButton();
        cmdLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setText("Welcome");

        cmdBrowseProducts.setText("Browse Products");
        cmdBrowseProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBrowseProductsActionPerformed(evt);
            }
        });

        cmdViewOrders.setText("View my orders");
        cmdViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdViewOrdersActionPerformed(evt);
            }
        });

        cmdEditDetails.setText("Edit details");
        cmdEditDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditDetailsActionPerformed(evt);
            }
        });

        cmdUnregister.setText("Unregister from shop");
        cmdUnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUnregisterActionPerformed(evt);
            }
        });

        cmdLogout.setText("Log out");
        cmdLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmdEditDetails)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdLogout)
                        .addGap(56, 56, 56)
                        .addComponent(lblWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdUnregister)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdBrowseProducts)
                                    .addComponent(cmdViewOrders))))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWelcome)
                    .addComponent(cmdLogout))
                .addGap(42, 42, 42)
                .addComponent(cmdBrowseProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdViewOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdEditDetails)
                .addGap(18, 18, 18)
                .addComponent(cmdUnregister)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLogoutActionPerformed
        CustomerLogin cl = new CustomerLogin();
        this.dispose();
        cl.setVisible(true);
    }//GEN-LAST:event_cmdLogoutActionPerformed

    private void cmdBrowseProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBrowseProductsActionPerformed
        ViewProducts vp = new ViewProducts(customer);
        this.dispose();
        vp.setVisible(true);
    }//GEN-LAST:event_cmdBrowseProductsActionPerformed

    private void cmdEditDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditDetailsActionPerformed
        EditCustomer ec = new EditCustomer(customer);
        this.dispose();
        ec.setVisible(true);
    }//GEN-LAST:event_cmdEditDetailsActionPerformed

    private void cmdUnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUnregisterActionPerformed
        DBManager db = new DBManager();
        db.deleteCustomer(customer);
        
        MainMenu mm = new MainMenu();
        this.dispose();
        mm.setVisible(true);
    }//GEN-LAST:event_cmdUnregisterActionPerformed

    private void cmdViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdViewOrdersActionPerformed
        CustomerPreviousOrder cpo = new CustomerPreviousOrder(customer);
        this.dispose();
        cpo.setVisible(true);
    }//GEN-LAST:event_cmdViewOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHome(customer).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBrowseProducts;
    private javax.swing.JButton cmdEditDetails;
    private javax.swing.JButton cmdLogout;
    private javax.swing.JButton cmdUnregister;
    private javax.swing.JButton cmdViewOrders;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
