/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import models.Staff;

/**
 *
 * @author Aidan
 */
public class StaffHome extends javax.swing.JFrame {

    //logged in staffS
    private static Staff staff;
    
    /**
     * Creates new form StaffHome
     */
    public StaffHome(Staff s) {
        this.staff = s;
        initComponents();
        this.setLocationRelativeTo(null);
        lblWelcome.setText(s.displayGreeting());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdModifyProducts = new javax.swing.JButton();
        cmdViewAllOrders = new javax.swing.JButton();
        cmdLogout = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdModifyProducts.setText("Modify products");
        cmdModifyProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModifyProductsActionPerformed(evt);
            }
        });

        cmdViewAllOrders.setText("View all orders");
        cmdViewAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdViewAllOrdersActionPerformed(evt);
            }
        });

        cmdLogout.setText("Log out");
        cmdLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLogoutActionPerformed(evt);
            }
        });

        lblWelcome.setText("Welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdViewAllOrders)
                    .addComponent(cmdModifyProducts))
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblWelcome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdLogout)
                .addGap(18, 18, 18)
                .addComponent(lblWelcome)
                .addGap(27, 27, 27)
                .addComponent(cmdModifyProducts)
                .addGap(35, 35, 35)
                .addComponent(cmdViewAllOrders)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //log staff memeber out, return to login page
    private void cmdLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLogoutActionPerformed
        StaffLogin sl = new StaffLogin();
        this.dispose();
        sl.setVisible(true);
    }//GEN-LAST:event_cmdLogoutActionPerformed

    //load modify products page
    private void cmdModifyProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModifyProductsActionPerformed
        ModifyProducts vps = new ModifyProducts(staff);
        this.dispose();
        vps.setVisible(true);
    }//GEN-LAST:event_cmdModifyProductsActionPerformed

    //load view all orders page
    private void cmdViewAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdViewAllOrdersActionPerformed
        StaffViewAllOrders svao = new StaffViewAllOrders(staff);
        this.dispose();
        svao.setVisible(true);
    }//GEN-LAST:event_cmdViewAllOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffHome(staff).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdLogout;
    private javax.swing.JButton cmdModifyProducts;
    private javax.swing.JButton cmdViewAllOrders;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
